### ISSUE TITLE
Shell injection in buffer-watcher

### ISSUE THREAD

**Issue by cpitclaudel** [NicolasPetton/emacs.d#1]
`buffer-watcher` should probably use `shell-quote-argument` on https://github.com/NicolasPetton/emacs.d/blob/master/local-packages/buffer-watcher/buffer-watcher.el#L72 ; as it stands, one can use a carefully crafted file name to run arbitrary commands.

**Comment by NicolasPetton** [comment]
Indeed, thanks!
